#mongodb
spring:
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      authentication-database: admin
      username: ${DB_USER}
      password: ${DB_PASS}
      database: courses-async
  rabbitmq:
    addresses: ${RABBITMQ_URL}