#microservice
server:
  port: 8090

api:
  controller:
    path: /course-service
  broker:
    exchange:
      userEvent: ead.userevent
    queue:
      userEventQueue: ead.userevent.ms.course


#mongodb
spring:
  application:
        name: course-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    openfeign:
      autoconfiguration:
        jackson:
          enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    prefer-ip-address: true
